---
- name: Debug OS family
  ansible.builtin.debug:
    var: ansible_os_family

- name: Update apt/dnf cache
  ansible.builtin.package:
    update_cache: yes

- name: Install required packages (Ubuntu)
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - mariadb-server
      - wget
      - unzip
    state: present
  when: ansible_os_family == "Debian"

- name: Install required packages (Rocky / RHEL)
  ansible.builtin.dnf:
    name:
      - httpd
      - php
      - php-mysqlnd
      - mariadb-server
      - wget
      - unzip
    state: present
  when: ansible_os_family in ["RedHat", "Rocky"]

- name: Remove default index.html
  ansible.builtin.file:
    path: "{{ wordpress_dir }}/index.html"
    state: absent

- name: Collect service facts
  ansible.builtin.service_facts:

- name: Start Apache (Ubuntu)
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  when: ansible_os_family == "Debian"
  notify: Restart Apache

- name: Start Apache (Rocky)
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
  when: ansible_os_family in ["RedHat", "Rocky"]
  notify: Restart Apache

- name: Start MariaDB (Ubuntu)
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Start MariaDB (Rocky)
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  when: ansible_os_family in ["RedHat", "Rocky"]

- name: Wait for MariaDB to start
  ansible.builtin.pause:
    seconds: 10
