---
# tasks/main.yml
- name: Update package cache
  ansible.builtin.package:
    update_cache: true

- name: Install packages on Debian
  ansible.builtin.apt:
    name: "{{ package_list_debian }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install packages on RedHat
  ansible.builtin.dnf:
    name: "{{ package_list_redhat }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Remove default index.html
  ansible.builtin.file:
    path: "{{ wordpress_install_dir }}/index.html"
    state: absent

- name: Start Apache on Debian
  ansible.builtin.service:
    name: "{{ apache_service_name_debian }}"
    state: started
    enabled: true
  when: ansible_os_family == 'Debian'
  notify: Restart Apache

- name: Start Apache on RedHat
  ansible.builtin.service:
    name: "{{ apache_service_name_redhat }}"
    state: started
    enabled: true
  when: ansible_os_family == 'RedHat'
  notify: Restart Apache

- name: Ensure MariaDB is started
  ansible.builtin.service:
    name: "{{ mariadb_service_name }}"
    state: started
    enabled: true

- name: Secure MariaDB - set root password
  ansible.builtin.mysql_user:
    login_user: root
    login_password: ''
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    state: present
  when: secure_mysql

- name: Remove anonymous MySQL users
  ansible.builtin.mysql_user:
    name: ''
    host_all: true
    state: absent
  when: mysql_remove_anonymous_users

- name: Remove test database
  ansible.builtin.mysql_db:
    name: test
    state: absent
  when: mysql_remove_test_db

- name: Reload MySQL privileges
  ansible.builtin.mysql_db:
    name: '*.*'
    state: reload
  when: mysql_reload_privileges